# Generated by Django 4.0.5 on 2022-06-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseRegistration',
            fields=[
                ('courseId', models.IntegerField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('professorId', models.IntegerField(max_length=15)),
                ('professorName', models.CharField(max_length=50)),
                ('courseCreateDate', models.DateField()),
            ],
        ),
    ]
