# Generated by Django 4.0.5 on 2022-06-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAPI', '0002_alter_courseregistration_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='professorId',
            field=models.IntegerField(),
        ),
    ]
