# Generated by Django 4.0.5 on 2022-07-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAPI', '0003_alter_courseregistration_professorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='professorDetails',
            fields=[
                ('proId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('proFName', models.CharField(max_length=50)),
                ('proLName', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=20)),
                ('yearJoin', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
