# Generated by Django 4.0.5 on 2022-07-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAPI', '0005_alter_professordetails_proid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professordetails',
            name='proId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
