# Generated by Django 4.0.5 on 2022-07-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAPI', '0007_alter_professordetails_yearjoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentDetails',
            fields=[
                ('stuId', models.IntegerField(primary_key=True, serialize=False)),
                ('stuFName', models.CharField(max_length=50)),
                ('stuLName', models.CharField(max_length=50)),
                ('courseId', models.CharField(max_length=20)),
                ('yearJoin', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
