# Generated by Django 4.0.5 on 2022-07-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAPI', '0008_studentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('assgnId', models.AutoField(primary_key=True, serialize=False)),
                ('assgnName', models.CharField(max_length=50)),
                ('assgnCreated', models.DateField()),
                ('assgnDeadline', models.DateField()),
                ('proId', models.IntegerField()),
                ('courseId', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='courseId',
            field=models.CharField(max_length=50),
        ),
    ]
