# Generated by Django 4.0.5 on 2022-08-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAPI', '0009_assignments_alter_studentdetails_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='DocFileName',
            field=models.CharField(default='file', max_length=100),
            preserve_default=False,
        ),
    ]
