# Generated by Django 4.0.5 on 2022-09-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAPI', '0012_alter_avgsimscore_avgsim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='avgSimScore',
        ),
        migrations.AddField(
            model_name='assignments',
            name='avgSim',
            field=models.FloatField(default=0.2),
            preserve_default=False,
        ),
    ]
