# Generated by Django 4.0.5 on 2022-09-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAPI', '0013_delete_avgsimscore_assignments_avgsim'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
