# Generated by Django 4.0.5 on 2022-09-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAPI', '0014_assignments_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='professordetails',
            name='simThreshold',
            field=models.FloatField(default=0.6),
            preserve_default=False,
        ),
    ]
