# Generated by Django 4.0.5 on 2022-10-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAPI', '0017_alter_studentdetails_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='index',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
